
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: QEmotionProjectV2_development


test:
  <<: *default
  database: QEmotionProjectV2_test


production:
  <<: *default
  database: qemotion_prod
  username: qemotion
  url: <%= ENV['DATABASE_URL'] %>